const $=(s,c=document)=>c.querySelector(s), $$=(s,c=document)=>[...c.querySelectorAll(s)];
const state={user:JSON.parse(localStorage.getItem('tr_user')||'null'),interests:JSON.parse(localStorage.getItem('tr_interests')||'null')||[
{id:crypto.randomUUID(),name:'GTA 6',keywords:['gta 6','gta vi','rockstar games','trailer gta 6'],priority:'high',active:true,image:'https://images.unsplash.com/photo-1605901309584-818e25960a8f?auto=format&fit=crop&w=300&q=80'},
{id:crypto.randomUUID(),name:'Marvel',keywords:['marvel','mcu','vingadores','marvel studios'],priority:'high',active:true,image:'https://images.unsplash.com/photo-1612036782180-6f0b6cd846fe?auto=format&fit=crop&w=300&q=80'},
{id:crypto.randomUUID(),name:'Neymar',keywords:['neymar','seleção brasileira','santos'],priority:'medium',active:true,image:'https://images.unsplash.com/photo-1579952363873-27f3bade9f55?auto=format&fit=crop&w=300&q=80'},
{id:crypto.randomUUID(),name:'PlayStation',keywords:['playstation 5','ps5','sony'],priority:'medium',active:true,image:'https://images.unsplash.com/photo-1606144042614-b2417e99c4e3?auto=format&fit=crop&w=300&q=80'},
{id:crypto.randomUUID(),name:'OpenAI',keywords:['openai','chatgpt','inteligência artificial'],priority:'low',active:true,image:'https://images.unsplash.com/photo-1677442136019-21780ecad995?auto=format&fit=crop&w=300&q=80'},
{id:crypto.randomUUID(),name:'Netflix',keywords:['netflix','lançamentos netflix','séries'],priority:'low',active:true,image:'https://images.unsplash.com/photo-1574375927938-d5a98e8ffe85?auto=format&fit=crop&w=300&q=80'},
{id:crypto.randomUUID(),name:'Apple',keywords:['apple','iphone','macbook','ios'],priority:'low',active:true,image:'https://images.unsplash.com/photo-1621768216002-5ac171876625?auto=format&fit=crop&w=300&q=80'}],news:JSON.parse(localStorage.getItem('tr_news')||'[]'),page:'dashboard'};
const save=()=>{localStorage.setItem('tr_interests',JSON.stringify(state.interests));localStorage.setItem('tr_news',JSON.stringify(state.news.slice(0,250)));};
const toast=m=>{const t=$('#toast');t.textContent=m;t.classList.add('show');setTimeout(()=>t.classList.remove('show'),2500)};
const esc=s=>String(s||'').replace(/[&<>'"]/g,m=>({'&':'&amp;','<':'&lt;','>':'&gt;',"'":'&#39;','"':'&quot;'}[m]));
const fmtDate=d=>new Intl.DateTimeFormat('pt-BR',{dateStyle:'short',timeStyle:'short'}).format(new Date(d));
const priorityLabel=p=>p==='high'?'Alta':p==='medium'?'Média':'Baixa';
function scoreNews(item,interest){let s=0,t=(item.title+' '+(item.description||'')).toLowerCase();if(t.includes(interest.name.toLowerCase()))s+=3;interest.keywords.forEach((k,i)=>{if(t.includes(k.toLowerCase()))s+=i===0?2:1});if(/oficial|lança|lançamento|confirmado|trailer|anuncia/.test(t))s+=1;const age=(Date.now()-new Date(item.publishedAt))/36e5;if(age<24)s+=1;if(/rockstar|openai|playstation|marvel|apple|netflix|globo|espn/.test((item.source||'').toLowerCase()))s+=1;return Math.min(10,s)}
async function apiSearch(q){const r=await fetch(`/api/news?q=${encodeURIComponent(q)}`);const data=await r.json().catch(()=>({}));if(!r.ok)throw new Error(data.error||'A API respondeu com erro.');return data.articles||[]}
async function refreshAll(show=false){const active=state.interests.filter(i=>i.active);let all=[];for(const i of active.slice(0,8)){try{const items=await apiSearch([i.name,...i.keywords.slice(0,2)].join(' OR '));items.forEach(n=>all.push({...n,interestId:i.id,interestName:i.name,score:scoreNews(n,i)}))}catch(e){if(show)toast(e.message);break}}const unique=new Map();[...all,...state.news].forEach(n=>unique.set(n.url||n.title,n));state.news=[...unique.values()].sort((a,b)=>new Date(b.publishedAt)-new Date(a.publishedAt)).slice(0,250);save();if(state.page==='dashboard')renderDashboard();updateCounts();if(show&&all.length)toast(`${all.length} notícias reais atualizadas.`);const critical=all.find(n=>n.score>=9);if(critical)browserNotify(critical)}
function browserNotify(n){if(Notification.permission==='granted')new Notification('🚨 ALERTA IMPORTANTE',{body:`${n.title}\nFonte: ${n.source} • Relevância ${n.score}/10`,icon:n.image||'icon.svg'});}
function showApp(){if(!state.user)return;$('#authView').classList.add('hidden');$('#appView').classList.remove('hidden');const first=state.user.name.split(' ')[0];$('#welcomeName').textContent=first;$('#sideName').textContent=first;$('#sideEmail').textContent=state.user.email;$('#avatarLetter').textContent=$('#topAvatar').textContent=first[0].toUpperCase();navigate('dashboard');setTimeout(()=>refreshAll(false),400)}
function navigate(page){state.page=page;$$('#nav button').forEach(b=>b.classList.toggle('active',b.dataset.page===page));const tpl=$(`#${page}Tpl`);if(!tpl)return;$('#pageHost').innerHTML='';$('#pageHost').append(tpl.content.cloneNode(true));$('#sidebar').classList.remove('open');bindPage();}
function bindPage(){if(state.page==='dashboard')renderDashboard();if(state.page==='interests'){renderInterests();$('#interestForm').onsubmit=addInterest;$('#sortInterests').onchange=renderInterests}if(state.page==='search'){$('#searchForm').onsubmit=manualSearch}if(state.page==='alerts')renderAlerts();if(state.page==='reports')renderReports();if(state.page==='settings'){$('#settingsForm').onsubmit=e=>{e.preventDefault();toast('Preferências salvas.');}}$$('[data-go]').forEach(b=>b.onclick=()=>navigate(b.dataset.go));}
function renderDashboard(){const active=state.interests.filter(i=>i.active), alerts=state.news.filter(n=>n.score>=7), recent=state.news.slice(0,10);$('#metricInterests').textContent=active.length;$('#metricAlerts').textContent=alerts.length;$('#metricNews').textContent=state.news.length;$('#metricTrending').textContent=Math.min(5,active.length);$('#donutTotal').firstChild.textContent=state.news.length;$('#interestCards').innerHTML=active.slice(0,4).map(i=>`<div class="interest-card"><img src="${esc(i.image)}"><div><strong>${esc(i.name)}</strong><span class="badge ${i.priority}">${priorityLabel(i.priority)}</span><span class="monitoring">Monitorando</span></div></div>`).join('')||'<p class="status">Nenhum interesse cadastrado.</p>';$('#latestNews').innerHTML=recent.slice(0,3).map(newsHTML).join('')||'<p class="status">Pesquise ou atualize seus interesses para carregar notícias reais.</p>';$('#importantAlerts').innerHTML=alerts.slice(0,3).map(alertHTML).join('')||'<p class="status">Nenhum alerta importante.</p>';$('#activityList').innerHTML=state.interests.slice(-5).reverse().map(i=>`<div>✦ Interesse monitorado: ${esc(i.name)} <time>agora</time></div>`).join('');const cats=[['Entretenimento',38,'#7f3cff'],['Esportes',25,'#1476e9'],['Games',18,'#0fb66f'],['Tecnologia',12,'#ff9c12'],['Outros',7,'#768299']];$('#categoryLegend').innerHTML=cats.map(c=>`<li><i style="background:${c[2]}"></i>${c[0]} <b>${c[1]}%</b></li>`).join('');updateCounts()}
function newsHTML(n){return `<div class="news-item"><img src="${esc(n.image||n.favicon||'icon.svg')}" onerror="this.src='icon.svg'"><div><b>${esc(n.title)}</b><p>${esc(n.source||'Fonte')} • ${fmtDate(n.publishedAt)}</p></div><div class="score">Relevância<br><strong>${n.score||0}/10</strong></div></div>`}
function alertHTML(n){return `<div class="alert-item ${n.score<9?'medium':''}"><div><b>${esc(n.title)}</b><p>${esc((n.description||'').slice(0,110))}</p><span>Fonte: ${esc(n.source||'Fonte')}</span></div><div class="score">${n.score}/10</div></div>`}
function renderInterests(){const sort=$('#sortInterests')?.value||'recent';let list=[...state.interests];if(sort==='name')list.sort((a,b)=>a.name.localeCompare(b.name));if(sort==='priority')list.sort((a,b)=>({high:0,medium:1,low:2}[a.priority]-({high:0,medium:1,low:2}[b.priority])));$('#interestCountBadge').textContent=list.filter(i=>i.active).length;$('#interestsRows').innerHTML=list.map(i=>`<div class="interest-row"><img src="${esc(i.image)}"><div><h4>${esc(i.name)}</h4><p>Palavras-chave: ${esc(i.keywords.join(', '))}</p><p>Fontes: <span class="source-count">ativas</span></p></div><div class="priority-cell"><span class="badge ${i.priority}">${priorityLabel(i.priority)}</span></div><label class="switch"><input type="checkbox" ${i.active?'checked':''} data-toggle="${i.id}"><span></span></label><button class="dots" data-delete="${i.id}">⋮</button></div>`).join('');$$('[data-toggle]').forEach(el=>el.onchange=()=>{const i=state.interests.find(x=>x.id===el.dataset.toggle);i.active=el.checked;save();renderInterests();updateCounts()});$$('[data-delete]').forEach(el=>el.onclick=()=>{if(confirm('Excluir este interesse?')){state.interests=state.interests.filter(x=>x.id!==el.dataset.delete);save();renderInterests();updateCounts()}})}
function addInterest(e){e.preventDefault();const name=$('#interestName').value.trim(),keywords=$('#interestKeywords').value.split(',').map(s=>s.trim()).filter(Boolean);state.interests.push({id:crypto.randomUUID(),name,keywords,priority:$('#interestPriority').value,active:$('#interestActive').checked,image:`https://www.google.com/s2/favicons?domain=${encodeURIComponent(name.toLowerCase().replace(/\s+/g,'')+'.com')}&sz=128`});save();e.target.reset();$('#interestActive').checked=true;renderInterests();toast('Interesse cadastrado.');refreshAll(false)}
async function manualSearch(e){e.preventDefault();const q=$('#searchInput').value.trim(),status=$('#searchStatus'),host=$('#searchResults');status.textContent='Buscando notícias reais...';host.innerHTML='';try{const items=await apiSearch(q);status.textContent=`${items.length} resultados encontrados.`;host.innerHTML=items.map(n=>`<article class="panel search-result"><img src="${esc(n.image||n.favicon||'icon.svg')}" onerror="this.src='icon.svg'"><div><h3>${esc(n.title)}</h3><small>${esc(n.source)} • ${fmtDate(n.publishedAt)}</small><p>${esc((n.description||'Sem resumo disponível.').slice(0,220))}</p><a target="_blank" rel="noopener" href="${esc(n.url)}">Abrir notícia original →</a></div></article>`).join('')||'<p>Nenhum resultado.</p>'}catch(err){status.textContent=err.message}}
function renderAlerts(){const a=state.news.filter(n=>n.score>=7);$('#allAlerts').innerHTML=a.map(n=>`<article class="panel">${alertHTML(n)}<small>${fmtDate(n.publishedAt)}</small></article>`).join('')||'<p class="status">Nenhum alerta gerado.</p>'}
function renderReports(){const a=state.news.filter(n=>n.score>=7);$('#reportsGrid').innerHTML=`<article class="panel"><small>Notícias analisadas</small><strong>${state.news.length}</strong></article><article class="panel"><small>Alertas gerados</small><strong>${a.length}</strong></article><article class="panel"><small>Interesses ativos</small><strong>${state.interests.filter(i=>i.active).length}</strong></article>`;const days=[...Array(7)].map((_,i)=>{const d=new Date();d.setDate(d.getDate()-(6-i));return d});const counts=days.map(d=>state.news.filter(n=>new Date(n.publishedAt).toDateString()===d.toDateString()).length);const max=Math.max(1,...counts);$('#reportBars').innerHTML=counts.map((c,i)=>`<div class="report-bar" style="height:${Math.max(8,c/max*100)}%"><span>${days[i].toLocaleDateString('pt-BR',{weekday:'short'})}</span></div>`).join('')}
function updateCounts(){const n=state.news.filter(x=>x.score>=7).length;['#navAlertCount','#topAlertCount'].forEach(s=>$(s)&&( $(s).textContent=n))}
$('#loginForm').onsubmit=e=>{e.preventDefault();state.user={name:$('#loginName').value.trim(),email:$('#loginEmail').value.trim()};localStorage.setItem('tr_user',JSON.stringify(state.user));showApp()};$('#createAccount').onclick=()=>toast('Preencha nome, e-mail e senha e clique em Entrar. A conta será criada neste dispositivo.');$('#togglePassword').onclick=()=>{const i=$('#loginPassword');i.type=i.type==='password'?'text':'password'};$('#logoutBtn').onclick=()=>{localStorage.removeItem('tr_user');location.reload()};$('#menuBtn').onclick=()=>$('#sidebar').classList.toggle('open');$('#themeBtn').onclick=()=>document.documentElement.classList.toggle('light');$('#notifyBtn').onclick=async()=>{if(!('Notification'in window))return toast('Seu navegador não oferece notificações.');const p=await Notification.requestPermission();toast(p==='granted'?'Notificações ativadas.':'Permissão não concedida.')};$('#globalSearch').onkeydown=e=>{if(e.key==='Enter'){navigate('search');setTimeout(()=>{$('#searchInput').value=e.target.value;$('#searchForm').requestSubmit()},0)}};document.addEventListener('keydown',e=>{if((e.ctrlKey||e.metaKey)&&e.key.toLowerCase()==='k'){e.preventDefault();$('#globalSearch').focus()}});$$('#nav button').forEach(b=>b.onclick=()=>navigate(b.dataset.page));if(state.user)showApp();
